# Site settings
title: 探索发现好玩的东西
motto: 不创造，不知道
email: bobz653@sina.com.cn
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bobz653.github.io" # the base hostname & protocol for your site
twitter_username: bobz653
github_username:  bobz653

# Build settings
markdown: kramdown
